set -g default-shell /opt/homebrew/bin/fish
set -g status off
set -g set-titles on
set -g set-titles-string "T: #T"
set -g mouse on
set -g history-limit 100000
set -g renumber-windows on
set -g status-keys vi
set -g escape-time 10

setw -g mode-keys vi

unbind-key -T copy-mode-vi v

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

set-hook -g window-linked 'if -F "#{==:#{session_windows},1}" "set status off" "set status on"'
set-hook -g window-unlinked 'if -F "#{==:#{session_windows},1}" "set status off" "set status on"'

set -g status-style bg="#4078f2",fg="#ffffff"
